### ISSUE TITLE
Design Doc - Questions

### ISSUE THREAD

**Issue by szymczdm** [taurheim/Fungi#1]
Please find below the list of questions customized for your group's design doc. There will likely be other things you may need to address, but this should get your thinking started.

---------

Keep your requirements in mind while addressing how you're going to implement your game. How are you going to implement specific features? And what decisions have you made regarding that implementation? You can point me to code/comments as necessary, but make sure it's clear why you've made that choice.

Examples of the kinds of things you should be thinking about follow:

How do your players play a co-op game? Is it couch co-op, LAN, or online? How will communication be handled? How do the players choose which role to take on? How will view-synchronization be handled?

How do players join/host a game?

How does the camera system work? Is it perspective or orthogonal? First-person or third? Are there multiple cameras? Does the camera follow the player? How does it do that (algorithm)? Can the player control the camera? If so, how?

What do your levels look like? What are the puzzles/obstacles/enemies in each? What is the goal of each level? Are they all the same or different? How does the story progress between levels? For each puzzle, how is a player expected to solve it? Are there multiple solutions? 

How does a player beat a level? Be specific for each type of level.

Is there a map? How does it work? Can the player see the whole thing from the beginning or is it obscured? How do they reveal more of it? How do they look at it? Does the game pause while they look at it? What is shown on the map?

What does "pausing" the game do? What will the player see when it's paused?
What do your menus look like? Will the game continue playing in the background (ex. GoldenEye 64 watch system), or will it freeze?

How does each player fail a level? What happens when they do? How do they continue?

How do players interact with other players/NPCs/objects/enemies? How far away should they be? Do they need to press a specific button or is it automatic once within a given range? What are the specific types of interactions possible and how do they work?

How does your level tracking system work? Does it save/load the game state? Does the game autosave? Are there checkpoints and how do they work?

When dealing with player movement state which keys will be mapped to which movement direction. Are you using Unity's standard assets for movement controls? Are the controls configurable? How fast will the player move? Is there a lead-time before movement begins? Does movement ramp-up or does the player start at maximum speed? Can the player move in the air? etc.

What kind of events can catch the guards' attention? What happens when they do?

What do the different map grid nodes allow the alien player to do? What are all of their possible actions? What happens after a node is unlocked?

How does the suspicion system work for the alien player? What levels of suspicion trigger what results?

What are your different guard types (including sprites/models)? How do they work? Do they follow predictable patterns? AI? Some combination? Be specific with which guard does what. How do they react to the players? etc.

What algorithms are you using for pathfinding? AI? etc. If you're using your own algorithms, explain them. If you're using existing algorithms, name them and provide a source.

What do your menus look like? What options are available to the player? How many menus are there? Is there a level-select screen?

Can the player soft-lock the game and be forced to restart? How? Can you guarantee this won't happen? How?

When changing game settings, will the changes apply immediately or will they require the game to be restarted? Are the changes persistent? How? What settings can be changed?

**Comment by JacquesCarette** [comment]
You shouldn't just close issues without comment.  You should, for example, link to where everything is 'fixed' - this case, to the commit where the design doc was added.

**Comment by taurheim** [comment]
Design Dog added to wiki - see https://github.com/taurheim/Fungi/wiki/Design-Document/8ee5505619d010e02411a7324922c5bf39a58e0c
