### ISSUE TITLE
NPC’s keep moving in a circle

### ISSUE THREAD

**Issue by k-abdelmesih** [taurheim/Fungi#10]
If you wait for too long the NPS’s keep moving in a circle (not going in with luscious hair or coming out  with a shiny head).

<img width="376" alt="screen shot 2017-12-23 at 12 18 42 am" src="https://user-images.githubusercontent.com/22666892/34317176-dd564bfc-e776-11e7-8224-49ca419a51b9.png">
<img width="378" alt="screen shot 2017-12-23 at 12 18 46 am" src="https://user-images.githubusercontent.com/22666892/34317177-dd63c2f0-e776-11e7-88f2-8ecb8a1411dc.png">

**Comment by ChrisCagna** [comment]
All NPC related issues have been resolved.
