### ISSUE TITLE
The building is open/escapable?

### ISSUE THREAD

**Issue by k-abdelmesih** [taurheim/Fungi#11]
The human can leave the building and they instantly are off the alien's radar.

<img width="422" alt="screen shot 2017-12-23 at 12 19 33 am" src="https://user-images.githubusercontent.com/22666892/34317181-fb06fd9a-e776-11e7-9956-a65dcb2c9506.png">
<img width="501" alt="screen shot 2017-12-23 at 12 19 38 am" src="https://user-images.githubusercontent.com/22666892/34317182-fb14b052-e776-11e7-8490-e74d44d498f6.png">

**Comment by JosephAQM** [comment]
Thanks. Fixed in commit b4c1df7789254ff2e3c767beecc515b791371e47.
