### ISSUE TITLE
Suggestion: Use a different background for the supporting players device screen because its using the same background as the whole screens background also make it look less bland.  

### ISSUE THREAD

**Issue by zahids4** [taurheim/Fungi#115]
<img width="912" alt="screen shot 2018-01-10 at 11 27 48 pm" src="https://user-images.githubusercontent.com/11669872/34808612-f846e200-f65d-11e7-9e90-751af258c661.png">

To give the payer a more authentic feel that they are looking at futuristic device use a different background. You can see on the bottom left corner of the device screen that its using the same background. Also aesthetically making the device look better and futuristic will help.

**Comment by bickybee** [comment]
Will consider for future visual polish but closing as that's not our focus now
