### ISSUE TITLE
In Level 2 the giant device is just floating in mid air.

### ISSUE THREAD

**Issue by zahids4** [taurheim/Fungi#118]
<img width="912" alt="screen shot 2018-01-10 at 11 37 01 pm" src="https://user-images.githubusercontent.com/11669872/34808813-3b7781aa-f65f-11e7-8ce8-6635524d9384.png">
This object doesnt seems to be suspended in mid air without any support. Adding a bar to make it seem like its being held up will look a lot better

**Comment by ChrisCagna** [comment]
SO!? IT'S MAGIC!
