### ISSUE TITLE
Level 4 No collision box on the Tree

### ISSUE THREAD

**Issue by gabrielcastagner** [taurheim/Fungi#123]
If you walk into the tree or hit a ball into the tree, then the objects go right through.  You could implement a simple collision box that covers the bottom half of the tree for optimization.

**Comment by szymczdm** [comment]
Why was this closed without comment?

**Comment by gabrielcastagner** [comment]
Hey Dan!

I accidentally copy pasted the bugs in the wrong group section so I removed
them because they were not the correct issue for  the corresponding group.
I will include that in the comment next time for less confusion.
