### ISSUE TITLE
Game continuation after game closure 

### ISSUE THREAD

**Issue by gabrielcastagner** [taurheim/Fungi#125]
When a new local game is initialized and then closed after a period of time, a creation of a new game instantiates the enemy at the opposite side of the map. This indicates that the game must still be active even when a game is closed, which may give some undesired consequences.

**Comment by taurheim** [comment]
Fixed in https://github.com/taurheim/Fungi/commit/182edacb81ac30d66a433d4bcca7ea3fa35a306d and https://github.com/taurheim/Fungi/commit/b41f4d2744aef3513451f3c1e39a3ad5476dff9d
