### ISSUE TITLE
The alien player should not see the map before the game begins

### ISSUE THREAD

**Issue by k-abdelmesih** [taurheim/Fungi#13]
This distinguishes between modes and strengthens their discoverability.

<img width="478" alt="screen shot 2017-12-23 at 12 20 34 am" src="https://user-images.githubusercontent.com/22666892/34317190-1c7dd854-e777-11e7-93a1-7386f781cf1d.png">

**Comment by taurheim** [comment]
Fixed as of https://github.com/taurheim/Fungi/commit/182edacb81ac30d66a433d4bcca7ea3fa35a306d
