### ISSUE TITLE
Handing in your executable

### ISSUE THREAD

**Issue by szymczdm** [taurheim/Fungi#2]
Please let me know (through this issue) how you would like to hand in your executable. If you plan on handing me a USB, we will need to schedule a time and place to exchange it.

If you'll be hosting it on a server or web-based service (Dropbox/Google Drive), leave a comment here to let me know which, then add another comment with the location here once you've uploaded it (you should also ensure this link is submitted on Avenue).

Note: If you can, please have both a Windows and MacOS build available.

**Comment by taurheim** [comment]
We will host it on OneDrive, here is the location we will put it in (we will have both a MacOS and Windows build)

https://1drv.ms/f/s!AlcpgC53gtHeit8kNmvRuwSaibEg4g
