### ISSUE TITLE
Got out of level 1

### ISSUE THREAD

**Issue by puruj** [taurheim/Fungi#21]
Went through first image and got outside of map.
![image](https://user-images.githubusercontent.com/6410204/34511394-34ac9554-f029-11e7-99ae-272b84b8738e.png)

![image](https://user-images.githubusercontent.com/6410204/34511374-1bbaba80-f029-11e7-9b97-34754e3a27ab.png)

**Comment by JosephAQM** [comment]
Duplicate of issue #16
