### ISSUE TITLE
Texture on wall in level one bug out

### ISSUE THREAD

**Issue by puruj** [taurheim/Fungi#22]
If you move camera on texture the color on texture flickers.
![image](https://user-images.githubusercontent.com/6410204/34511431-919157be-f029-11e7-978e-a2b7ec35e547.png)
![image](https://user-images.githubusercontent.com/6410204/34511440-a2fc4df6-f029-11e7-9779-e472037f2cbc.png)

**Comment by JosephAQM** [comment]
Thanks. Fixed in 8457ed4f12591d40804d15c66b76e6f8767bbe0b.
