### ISSUE TITLE
Can Jump glitch out of Level 2

### ISSUE THREAD

**Issue by puruj** [taurheim/Fungi#26]
If you get past the first puzzle door ,then jump on the object on the first picture and then jump on to wall. This will morph the player outside of the map. 
![image](https://user-images.githubusercontent.com/6410204/34511926-deb80c9c-f02c-11e7-9289-29074069ea66.png)
![image](https://user-images.githubusercontent.com/6410204/34511942-eeaa9926-f02c-11e7-926f-6ef86189a505.png)

**Comment by JosephAQM** [comment]
Thanks, fixed in 107b568835da8b5cde49c37d2cda7ccf40003121.
