### ISSUE TITLE
Can glitch on top of invisible barrier in level 3

### ISSUE THREAD

**Issue by puruj** [taurheim/Fungi#32]
I sprint jumped from the table in first picture on to invisible barrier .
![image](https://user-images.githubusercontent.com/6410204/34512217-dcc1a220-f02e-11e7-849d-1c57a2acd3e5.png)

![image](https://user-images.githubusercontent.com/6410204/34512242-0498b09a-f02f-11e7-9b09-79589ba34944.png)

**Comment by ChrisCagna** [comment]
Props in this area have been adjusted, and this glitch jump could not be reproduced.
