### ISSUE TITLE
I can clip out of bounds and get out of the map

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#35]
![image](https://user-images.githubusercontent.com/14252147/34539746-d7492bf8-f09f-11e7-8e1f-41f53332a9ef.png)

**Comment by thatstoofar** [comment]
![image](https://user-images.githubusercontent.com/14252147/34539759-e79b8e7e-f09f-11e7-89dd-d5436ca492b1.png)

**Comment by taurheim** [comment]
Duplicate of #11
