### ISSUE TITLE
Map does not match actual layout of level for the first level

### ISSUE THREAD

**Issue by junhao-wang** [taurheim/Fungi#59]
In the first level, there are many additional "exits" that are not explicitly marked on the map, these should either be sealed, or the map should be updated to reflect their existence. In the case of an unimplemented feature, an alternate indication on the map (such as a red line segment) could also work.

**Comment by JosephAQM** [comment]
Thanks. Fixed in commit b4c1df7789254ff2e3c767beecc515b791371e47.
