### ISSUE TITLE
No Description provided for Level 2 Door Symbol

### ISSUE THREAD

**Issue by Zyanting18** [taurheim/Fungi#60]
Not sure what's the difference between any of these buttons.
![image](https://user-images.githubusercontent.com/31933239/34551058-0eb40efc-f0e4-11e7-9bb8-ac1efb32b882.png)

**Comment by taurheim** [comment]
This is intended - it's one of the puzzles. I'll point this to #7, if there is confusion then we probably need to make this more discoverable.
