### ISSUE TITLE
Host disconnection causes clients to freeze.

### ISSUE THREAD

**Issue by junhao-wang** [taurheim/Fungi#61]
When a host disconnects from the game, the client game freezes instead of going to the main menu or react in a responsive way.

**Comment by taurheim** [comment]
Fixed in https://github.com/taurheim/Fungi/commit/182edacb81ac30d66a433d4bcca7ea3fa35a306d and https://github.com/taurheim/Fungi/commit/b41f4d2744aef3513451f3c1e39a3ad5476dff9d - Either player disconnecting causes the game to boot to the home screen.
