### ISSUE TITLE
Door can be only closed by pressing right top corner button

### ISSUE THREAD

**Issue by Zyanting18** [taurheim/Fungi#63]
Not sure why only the right top corner can open/close door
![image](https://user-images.githubusercontent.com/31933239/34551109-83a83b3e-f0e4-11e7-94f1-d4377405e9b5.png)

**Comment by JosephAQM** [comment]
It is unclear right now, but the point of the puzzle is to find the symbol that appears on both the buttons and the alien UI. We will be adding some sort of instruction for this.

**Comment by taurheim** [comment]
Tagging #7
