### ISSUE TITLE
Possible for Host to start game with unmatching level selection

### ISSUE THREAD

**Issue by ldkjf2nd** [taurheim/Fungi#67]
Host selected level 1 and client selected level 3. The client game will not start, while spawning a player each time for the host.

![image](https://user-images.githubusercontent.com/14301313/34569911-35462c40-f138-11e7-8a89-115f8da4537d.png)

**Comment by taurheim** [comment]
Fixed in https://github.com/taurheim/Fungi/commit/249ab92566b349252d7c71484aae3c0072507e50 - Level selection is now synced across clients.
