### ISSUE TITLE
Lack of menus and features ingame

### ISSUE THREAD

**Issue by ldkjf2nd** [taurheim/Fungi#68]
Should include pause menu and options once game starts.
Should include options to adjust audio level or return to main page.

**Comment by JosephAQM** [comment]
Thanks. The following features have been added:
1. Audio level adjustment in ed7e63143ae2b4e202a41931ffc10374a51f3032
2. Pause functionality in c743d4edb5a105fdc97de5b6eac6c7bc601077a5
3. Return to Main Menu in a87e3b24a21be335956734e4bedc71676aa461d6
