### ISSUE TITLE
The camera scrolling stops moving when the mouse stops moving

### ISSUE THREAD

**Issue by k-abdelmesih** [taurheim/Fungi#8]
This might be a personal preference, but if the mouse is held at the edge of the screen then the camera should keep on moving. Similar to scrolling or dragging something down a file explorer. What can be done is adding an option to adjust such velocity so that each player is satisfied.

**Comment by taurheim** [comment]
Upon further review I don't really understand what you mean - the alien view does not scroll and the human view is in first-person mode, where the mouse is (necessarily) centered on the screen at all times.
