### ISSUE TITLE
Possible for network menu to disappear on clicks 

### ISSUE THREAD

**Issue by thatstoofar** [taurheim/Fungi#87]
If you keep clicking into LAN host server and stop. Eventually the network menu will disappear forever

![image](https://user-images.githubusercontent.com/14252147/34588774-c59ec68c-f17c-11e7-8c57-46fd927d1128.png)

**Comment by taurheim** [comment]
The menu was removed in https://github.com/taurheim/Fungi/commit/0076528b5b538b4ee21264251583b5cad99e5e99 - This bug no longer exists.
