### ISSUE TITLE
More than 2 players can play

### ISSUE THREAD

**Issue by k-abdelmesih** [taurheim/Fungi#9]
I tried hosting once and joining twice, I had 2 games running as the human.

<img width="522" alt="screen shot 2017-12-23 at 12 17 56 am" src="https://user-images.githubusercontent.com/22666892/34317173-c2ec4b18-e776-11e7-88a1-36192914b7d5.png">

**Comment by taurheim** [comment]
Fixed in https://github.com/taurheim/Fungi/commit/10502261cd7785d41a516983bc897842246f5116
